name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dev  # Add other branches if needed

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4 
 
      - name: Set Up SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
          echo "Deploying branch: $BRANCH_NAME"

          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            #rm -rf /web_branch/branches/* #deleting current releases to save space on EC2, need to remove it 
            #cd /home/ec2-user/deployer && dep deploy:unlock && dep deploy --branch=${BRANCH_NAME} 
            #copy file to s3
            #aws s3 scp /web_branch/archives/${BRANCH_NAME}.tar.gz s3://csm-access-github-actions-poc-builds/qa/
            
            # sudo chown -R ${{ secrets.EC2_USER }}:$(whoami) /var/www/html/${BRANCH_NAME} 
          EOF

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Copy File from S3
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
          aws s3 cp s3://csm-access-github-actions-poc-builds/qa/${BRANCH_NAME}.tar.gz  .

      - name: Extract the Archive
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
          tar -xzvf ${BRANCH_NAME}.tar.gz -C /var/www/html/vcsdatabase.com/current/
