on:
  push:
    branches:
      - aws_poc
      - dev  # Add other branches if needed

jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
 
      - name: Set Up SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          BRANCH_NAME=$(echo ${GITHUB_REF##*/})
          echo "Deploying branch: $BRANCH_NAME"

          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            # Tar and prepare the file for upload
            tar -czf /web_branch/archives/${BRANCH_NAME}.tar.gz -C /var/www/html/${BRANCH_NAME} .

            echo "File compressed: /web_branch/archives/${BRANCH_NAME}.tar.gz"
          EOF

      - name: Copy to S3
        run: |
          scp -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/web_branch/archives/${{ github.ref_name }}.tar.gz .
          aws s3 cp ${{ github.ref_name }}.tar.gz s3://csm-access-github-actions-poc-builds/qa/

      - name: Cleanup Local File
        run: rm -f ${{ github.ref_name }}.tar.gz
